apiVersion: v1
kind: Pod
metadata:
  labels:
    build-pipeline: kubernetes-test
spec:
  containers:
  - name: maven
    image: maven:alpine
    command:
    - cat
    tty: true
  - name: busybox
    image: busybox
    command:
    - cat
    tty: true
